server:
  port: 8000
zuul:
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      url: http://mircoservice:8080/multiplications
    results:
      path: /results/**
      url: http://mircoservice:8080/results
    leaders:
      path: /leaders/**
      url: http://gamification:8081/leaders
    stats:
      path: /stats/**
      url: http://gamification:8081/stats
  endpoints:
    trace:
      sensitive: false
  ribbon:
    eureka:
      enabled: false
