version: "3"

services:
  gateway:
    image: book/gateway
    ports:
      - "8000:8000"
    links:
      - mircoservice
      - gamification
  mircoservice:
    image: book/mircoservice  
    ports:
      - "8080:8080"
    links:
      - rabbitmq
  gamification:
    image: book/gamification  
    ports:
      - "8081:8081"
    links:
      - rabbitmq
  rabbitmq:
    image: bitnami/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USERNAME=fg
      - RABBITMQ_PASSWORD=fg